spring:
  application:
    name: spring-oauth2-client
  security:
    oauth2:
      client:
        registration:
          clientone:
            provider: "spring"
            client-id: "clientone"
            client-secret: "secret"
            authorization-grant-type: "authorization_code"
            client-authentication-method: "client_secret_basic"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - "user.read"
              - "user.write"
              - "openid"
        provider:
          spring:
            issuer-uri: http://localhost:9000
